/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BusinessDevelopmentRouteImport } from './routes/business-development'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as ContractsContractIdRouteImport } from './routes/contracts.$contractId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDevelopmentRoute = BusinessDevelopmentRouteImport.update({
  id: '/business-development',
  path: '/business-development',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdRoute = ContractsContractIdRouteImport.update({
  id: '/contracts/$contractId',
  path: '/contracts/$contractId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/business-development': typeof BusinessDevelopmentRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/people': typeof PeopleRoute
  '/procurement': typeof ProcurementRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/contracts/': typeof ContractsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/business-development': typeof BusinessDevelopmentRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/people': typeof PeopleRoute
  '/procurement': typeof ProcurementRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/contracts': typeof ContractsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/approvals': typeof ApprovalsRoute
  '/assets': typeof AssetsRoute
  '/business-development': typeof BusinessDevelopmentRoute
  '/documents': typeof DocumentsRoute
  '/finance': typeof FinanceRoute
  '/people': typeof PeopleRoute
  '/procurement': typeof ProcurementRoute
  '/risks': typeof RisksRoute
  '/settings': typeof SettingsRoute
  '/contracts/$contractId': typeof ContractsContractIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/contracts/': typeof ContractsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/approvals'
    | '/assets'
    | '/business-development'
    | '/documents'
    | '/finance'
    | '/people'
    | '/procurement'
    | '/risks'
    | '/settings'
    | '/contracts/$contractId'
    | '/projects/$projectId'
    | '/contracts/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/approvals'
    | '/assets'
    | '/business-development'
    | '/documents'
    | '/finance'
    | '/people'
    | '/procurement'
    | '/risks'
    | '/settings'
    | '/contracts/$contractId'
    | '/projects/$projectId'
    | '/contracts'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/approvals'
    | '/assets'
    | '/business-development'
    | '/documents'
    | '/finance'
    | '/people'
    | '/procurement'
    | '/risks'
    | '/settings'
    | '/contracts/$contractId'
    | '/projects/$projectId'
    | '/contracts/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AssetsRoute: typeof AssetsRoute
  BusinessDevelopmentRoute: typeof BusinessDevelopmentRoute
  DocumentsRoute: typeof DocumentsRoute
  FinanceRoute: typeof FinanceRoute
  PeopleRoute: typeof PeopleRoute
  ProcurementRoute: typeof ProcurementRoute
  RisksRoute: typeof RisksRoute
  SettingsRoute: typeof SettingsRoute
  ContractsContractIdRoute: typeof ContractsContractIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-development': {
      id: '/business-development'
      path: '/business-development'
      fullPath: '/business-development'
      preLoaderRoute: typeof BusinessDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId': {
      id: '/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof ContractsContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ApprovalsRoute: ApprovalsRoute,
  AssetsRoute: AssetsRoute,
  BusinessDevelopmentRoute: BusinessDevelopmentRoute,
  DocumentsRoute: DocumentsRoute,
  FinanceRoute: FinanceRoute,
  PeopleRoute: PeopleRoute,
  ProcurementRoute: ProcurementRoute,
  RisksRoute: RisksRoute,
  SettingsRoute: SettingsRoute,
  ContractsContractIdRoute: ContractsContractIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
